-- Steam 프로필 URL 및 기타 필드 추가
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS steam_profile_url TEXT,
ADD COLUMN IF NOT EXISTS steam_avatar_url TEXT,
ADD COLUMN IF NOT EXISTS steam_display_name TEXT,
ADD COLUMN IF NOT EXISTS steam_game_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS steam_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS steam_last_sync TIMESTAMP WITH TIME ZONE;